### ISSUE TITLE
API 'summary' and 'gpus' hash rate error

### ISSUE THREAD

**Issue by delawr0190** [zjazz/zjazz_cuda_miner#4]
Version:  zjazz_cuda_win64_0.971
Issue:  the 'summary' and 'gpus' responses contain an invalid conversion to KHS

Query:

`
echo "summary|" | netcat 192.168.3.194 4011
`

Response:

`
NAME=zjazz_cuda_win;VER=0.971;API=1.0;ALGO=bitcash;GPUS=8;KHS=2064.78;HS=2.0648;SOLV=7;ACC=7;REJ=0;ACCMN=0.000;DIFF=0.000003;NETKHS=0;POOLS=1;UPTIME=45;TS=1537755178|
`

HS = 2.0648
KHS = 2064.78

KHS should be 0.0020648

This is present in 'gpus' as well.

**Comment by delawr0190** [comment]
Also (unrelated - I can open another ticket, if needed).  Would it be possible to implement 'hwinfo' on the API?

**Comment by zjazz** [comment]
Hey! Thanks for your feedback.

**1) KHS scale**

About KHS scale, it has been scaled by 1000000 on purpose. Let me explain why:

Cuckoo algorithm hashrate is too low compared with standard hashing algorithms. As a result of very low hashrate values some monitoring software does not work properly when KHS is extremely low. So, from a practical point of view, to support a ccminer compatible API with existing monitoring software I decided to scale KHS to a 1000000 times higher value and added a new HS field with the proper value when a cuckoo algorithm is used.

If you know a better way to deal with this issue I'm open to change it.

**2) hwinfo**

About hwinfo API function, definitely it will available in the future but it's not a high priority for the next release. The main reason why hwinfo is not yet available is because the miner is not monitoring GPU hardware.

**Comment by delawr0190** [comment]
KHS scale:

Thank you for clearing that up.  I was under the impression that ccminer-like implied that it was to return the same key/value combinations, but now that I understand the introduction of the HS field, that makes sense.

hwinfo:

All good!  Able to proceed with gpus for now - was just verifying that it was somewhere on the radar, even if low.

Thanks for your work.
